version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '02:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    # Note: Team references removed as they may not exist in all repositories
    # Add specific usernames or recreate teams as needed:
    # reviewers:
    #   - 'username1'
    # assignees:
    #   - 'username2'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'security'

  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '02:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    # Note: Team references removed as they may not exist in all repositories
    # Add specific usernames or recreate teams as needed:
    # reviewers:
    #   - 'username1'
    # assignees:
    #   - 'username2'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'python'
      - 'security'
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    ignore:
      # Ignore major version updates for stability
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Node.js dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '02:00'
      timezone: 'UTC'
    open-pull-requests-limit: 10
    # Note: Team references removed as they may not exist in all repositories
    # Add specific usernames or recreate teams as needed:
    # reviewers:
    #   - 'username1'
    # assignees:
    #   - 'username2'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'npm'
      - 'security'
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'
    ignore:
      # Ignore major version updates for stability
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Note: Docker and Terraform ecosystems removed as no corresponding files exist in this template
  # Add them back when Dockerfile or *.tf files are added to the repository
